import json
import os


class FakeLLMClient:
    """Deterministic, offline fallback: composes a grounded answer from the
    recorded decision facts and retrieved chunks. No API key required."""

    name = "fake"

    def generate(self, decision_snapshot, chunks, question):
        decision_snapshot = decision_snapshot or {}
        outcome = decision_snapshot.get("decision")
        reasons = decision_snapshot.get("reason_codes") or []
        reason_text = "; ".join(reasons) if reasons else "no adverse reason codes were recorded"

        basis = []
        for c in chunks:
            label = c.get("rule_id") or c.get("section_path") or c.get("chunk_id")
            text = (c.get("chunk_text") or "").strip()
            claim = label
            if text:
                claim = f"{label}: {text.split('.')[0][:240]}"
            basis.append({"chunk_id": c.get("chunk_id"), "claim": claim})

        explanation = (
            f"The application was {outcome}. Recorded reason(s): {reason_text}. "
            "The applicable policy excerpts are cited below."
        )
        return {
            "status": "answered",
            "decision_outcome": outcome,
            "explanation": explanation,
            "policy_basis": basis,
            "limitations": ["Generated by the local fallback (no LLM API key configured)."],
        }


class OpenAILLMClient:
    name = "openai"

    def __init__(self, model=None, api_key=None, base_url=None):
        self.model = model or "gemini-3.6-flash"
        self.api_key = api_key
        self.base_url = base_url

    def generate(self, decision_snapshot, chunks, question):
        from openai import OpenAI

        from app.rag.prompts import SYSTEM_PROMPT, build_user_prompt

        client_kwargs = {}
        if self.api_key:
            client_kwargs["api_key"] = self.api_key
        if self.base_url:
            client_kwargs["base_url"] = self.base_url
        client = OpenAI(**client_kwargs)

        user_prompt = build_user_prompt(question, decision_snapshot, chunks)
        # Cache-friendly message order: the SYSTEM_PROMPT is a static, constant
        # prefix (cached across requests); all variable content (decision facts,
        # retrieved chunks, question) lives in the user message with the question
        # last. temperature=0 keeps output deterministic so identical prompts
        # also reuse the same cached completion where the provider supports it.
        resp = client.chat.completions.create(
            model=self.model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        )
        return json.loads(resp.choices[0].message.content)


def get_llm_client():
    """Return the configured LLM client.

    Any OpenAI-compatible free provider works (Gemini, Groq, Cerebras, OpenRouter,
    etc.) via these env vars (checked in priority order):

      LLM_API_KEY  (or GEMINI_API_KEY)
      LLM_BASE_URL (or GEMINI_BASE_URL)
      LLM_MODEL_ID (or GEMINI_MODEL_ID)

    With no key configured, returns the offline FakeLLMClient.
    """
    api_key = os.environ.get("LLM_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return FakeLLMClient()

    base_url = os.environ.get("LLM_BASE_URL") or os.environ.get("GEMINI_BASE_URL")
    model = (
        os.environ.get("LLM_MODEL_ID")
        or os.environ.get("GEMINI_MODEL_ID")
        or "gemini-3.6-flash"
    )
    return OpenAILLMClient(api_key=api_key, base_url=base_url, model=model)
