import json
import os


class FakeLLMClient:
    """Deterministic, offline fallback: composes a grounded answer from the
    recorded decision facts and retrieved chunks. No API key required."""

    name = "fake"

    def generate(self, decision_snapshot, chunks, question):
        outcome = decision_snapshot.get("decision")
        reasons = decision_snapshot.get("reason_codes") or []
        reason_text = "; ".join(reasons) if reasons else "no adverse reason codes were recorded"

        basis = []
        for c in chunks:
            label = c.get("rule_id") or c.get("section_path") or c.get("chunk_id")
            text = (c.get("chunk_text") or "").strip()
            claim = label
            if text:
                claim = f"{label}: {text.split('.')[0][:240]}"
            basis.append({"chunk_id": c.get("chunk_id"), "claim": claim})

        explanation = (
            f"The application was {outcome}. Recorded reason(s): {reason_text}. "
            "The applicable policy excerpts are cited below."
        )
        return {
            "status": "answered",
            "decision_outcome": outcome,
            "explanation": explanation,
            "policy_basis": basis,
            "limitations": ["Generated by the local fallback (no LLM API key configured)."],
        }


class OpenAILLMClient:
    name = "openai"

    def __init__(self, model=None, api_key=None, base_url=None):
        self.model = model or os.environ.get("OPENAI_MODEL_ID", "gpt-4o-mini")
        self.api_key = api_key
        self.base_url = base_url

    def generate(self, decision_snapshot, chunks, question):
        from openai import OpenAI

        from app.rag.prompts import SYSTEM_PROMPT, build_user_prompt

        client_kwargs = {}
        if self.api_key:
            client_kwargs["api_key"] = self.api_key
        if self.base_url:
            client_kwargs["base_url"] = self.base_url
        client = OpenAI(**client_kwargs)

        user_prompt = build_user_prompt(question, decision_snapshot, chunks)
        resp = client.chat.completions.create(
            model=self.model,
            temperature=0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        )
        return json.loads(resp.choices[0].message.content)


def get_llm_client():
    gemini_key = os.environ.get("GEMINI_API_KEY")
    if gemini_key:
        return OpenAILLMClient(
            api_key=gemini_key,
            base_url=os.environ.get(
                "GEMINI_BASE_URL", "https://generativelanguage.googleapis.com/v1beta/openai/"
            ),
            model=os.environ.get("GEMINI_MODEL_ID", "gemini-3.6-flash"),
        )
    if os.environ.get("OPENAI_API_KEY"):
        return OpenAILLMClient()
    return FakeLLMClient()
